/**
 * Generate `.github/copilot-instructions.md` from a selected preset.
 *
 * The generated file is the entry point GitHub Copilot loads at the start
 * of every session — it tells the agent which skills are available and
 * how to use them. We keep it intentionally short: links + a one-line
 * TLDR per skill (read from each SKILL.md's frontmatter `description`).
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";

import matter from "gray-matter";

import type { DojoProfile } from "./profile.js";

const HEADER = `<!--
  Generated by copilot-dojo. Do not edit by hand — re-run
  \`npx copilot-dojo init\` to refresh. The dojo is the source of
  truth: https://github.com/andreaswasita/copilot-agents-dojo
-->

# Copilot Agents — Project Instructions

This project follows the **Copilot Agents Dojo** discipline. Before doing any
work, agents MUST internalise the rules below and the skills listed in
\`skills/\`.

## Operating rules (non-negotiable)

1. **Plan before code.** Read \`skills/plan-before-code/SKILL.md\` and use it
   for any non-trivial change.
2. **Verify before done.** Every change is finished only when its own
   verification criterion has been re-run and passed.
3. **No commits without PR.** Always raise a pull request — never push to
   \`main\` directly. Branch protection enforces this.
4. **Update the profile.** If you add or remove skills, re-run
   \`npx copilot-dojo init\` so \`.dojo-profile.yml\` stays accurate.

## Skills loaded in this project
`;

const FOOTER = `

## How to add more skills

Browse the full catalogue at
<https://github.com/andreaswasita/copilot-agents-dojo/blob/main/skills.md>
and re-run \`npx copilot-dojo init --preset <id>\` (or pick \`custom\` once
the custom picker lands).
`;

interface AgentLine {
  id: string;
  line: string;
}

async function describeSkill(
  skillsRoot: string,
  id: string,
): Promise<AgentLine> {
  try {
    const raw = await readFile(join(skillsRoot, id, "SKILL.md"), "utf8");
    const fm = matter(raw).data as { description?: string };
    const desc = (fm.description ?? "").trim().replace(/\s+/g, " ");
    return { id, line: `- [\`${id}\`](../skills/${id}/SKILL.md) — ${desc || "(no description)"}` };
  } catch {
    return { id, line: `- \`${id}\` — *(file not found on disk; was it installed?)*` };
  }
}

async function describeAgent(
  agentsRoot: string,
  id: string,
): Promise<AgentLine> {
  try {
    const raw = await readFile(join(agentsRoot, `${id}.md`), "utf8");
    const fm = matter(raw).data as { brief?: string; description?: string };
    const blurb = (fm.brief ?? fm.description ?? "").trim().replace(/\s+/g, " ");
    return { id, line: `- [\`${id}\`](../agents/${id}.md) — ${blurb || "(no description)"}` };
  } catch {
    return { id, line: `- \`${id}\` — *(file not found on disk; was it installed?)*` };
  }
}

export async function renderInstructions(
  targetDir: string,
  profile: DojoProfile,
): Promise<string> {
  const skillsRoot = join(targetDir, "skills");
  const agentsRoot = join(targetDir, "agents");

  const skills = await Promise.all(
    profile.skills.map((id) => describeSkill(skillsRoot, id)),
  );
  const agents = await Promise.all(
    profile.agents.map((id) => describeAgent(agentsRoot, id)),
  );

  const sections: string[] = [HEADER];
  if (skills.length > 0) {
    sections.push(skills.map((s) => s.line).join("\n"));
  } else {
    sections.push("*(no skills selected)*");
  }
  if (agents.length > 0) {
    sections.push("\n## Agents (personas) available\n");
    sections.push(agents.map((a) => a.line).join("\n"));
  }
  sections.push(FOOTER);
  return sections.join("\n");
}
