/**
 * Read/write `.dojo-profile.yml` in a target project directory.
 *
 * Schema v1:
 *   version: 1
 *   preset: <PresetId>
 *   ref: <git ref the skills came from>
 *   skills: [<id>, ...]
 *   agents: [<id>, ...]
 *   installed_at: ISO-8601
 *   installer_version: <semver of copilot-dojo when this was written>
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import yaml from "yaml";

import type { PresetId } from "./presets.js";

export const PROFILE_FILENAME = ".dojo-profile.yml";

export interface DojoProfile {
  version: 1;
  preset: PresetId | "custom";
  ref: string;
  skills: string[];
  agents: string[];
  installed_at: string;
  installer_version: string;
}

export async function readProfile(
  targetDir: string,
): Promise<DojoProfile | null> {
  try {
    const raw = await readFile(join(targetDir, PROFILE_FILENAME), "utf8");
    const parsed = yaml.parse(raw);
    if (!parsed || typeof parsed !== "object") return null;
    if (parsed.version !== 1) {
      throw new Error(
        `.dojo-profile.yml has unsupported version ${parsed.version} (this installer speaks v1)`,
      );
    }
    return parsed as DojoProfile;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw err;
  }
}

export async function writeProfile(
  targetDir: string,
  profile: DojoProfile,
): Promise<string> {
  const path = join(targetDir, PROFILE_FILENAME);
  const header =
    "# Generated by copilot-dojo. Re-run `npx copilot-dojo init` to update.\n" +
    "# https://github.com/andreaswasita/copilot-agents-dojo\n";
  const body = yaml.stringify(profile, { lineWidth: 0 });
  await writeFile(path, header + body, "utf8");
  return path;
}
