"""Invariant tests for the generated slash-command prompt shims (G9).

These assert behaviour, not snapshots: every skill and persona has a shim,
the generator is idempotent (no drift), and each shim has the expected shape.
They never pin a specific count or description text, so legitimate edits to
skills/agents won't break them — only a stale prompt tree will.

CI runs the bash generator via `pytest -q tests/`; locally set DOJO_BASH to a
bash on PATH (e.g. Git Bash on Windows).
"""
from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BASH = os.environ.get("DOJO_BASH", "bash")
GEN = REPO_ROOT / "scripts" / "regen-prompts.sh"
PROMPTS = REPO_ROOT / ".github" / "prompts"


def _skill_ids() -> list[str]:
    return sorted(p.parent.name for p in (REPO_ROOT / "skills").glob("*/SKILL.md"))


def _agent_slugs() -> list[str]:
    return sorted(p.stem for p in (REPO_ROOT / "agents").glob("*.md"))


def test_generator_reports_no_drift() -> None:
    result = subprocess.run(
        [BASH, str(GEN), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=120,
    )
    assert result.returncode == 0, (
        "prompt shims are out of date — run `bash scripts/regen-prompts.sh`\n"
        f"{result.stdout}\n{result.stderr}"
    )


def test_one_shim_per_skill() -> None:
    for skill in _skill_ids():
        shim = PROMPTS / f"dojo-{skill}.prompt.md"
        assert shim.is_file(), f"missing slash-command shim for skill: {skill}"


def test_one_shim_per_agent() -> None:
    for slug in _agent_slugs():
        shim = PROMPTS / f"dojo-agent-{slug}.prompt.md"
        assert shim.is_file(), f"missing slash-command shim for agent: {slug}"


def test_no_orphan_shims() -> None:
    expected = {f"dojo-{s}.prompt.md" for s in _skill_ids()} | {
        f"dojo-agent-{a}.prompt.md" for a in _agent_slugs()
    }
    actual = {p.name for p in PROMPTS.glob("dojo-*.prompt.md")}
    assert actual == expected, f"orphan/missing shims: {actual ^ expected}"


def test_shim_shape() -> None:
    for shim in PROMPTS.glob("dojo-*.prompt.md"):
        text = shim.read_text(encoding="utf-8")
        assert text.startswith("---\n"), shim.name
        assert "mode: agent" in text, shim.name
        assert re.search(r"^description: ", text, re.M), shim.name
        assert "Auto-generated by scripts/regen-prompts.sh" in text, shim.name
