import { Hono } from "hono";
import { eq, ilike, and } from "drizzle-orm";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";
import { memoryEntries } from "@dojo/db";
import type { Db } from "@dojo/db";
import {
  scanAllMemory,
  readLinkGraph,
  buildGraphPayload,
  getBacklinksFor,
  getForwardLinksFor,
} from "../memory-scanner.js";

const VALID_TYPES = new Set(["decision", "pattern", "preference", "session"]);
const VALID_TYPE_FOLDERS: Record<string, string> = {
  decision: "decisions",
  pattern: "patterns",
  preference: "preferences",
  session: "sessions",
};

interface ScaffoldInput {
  type: string;
  slugSuffix: string;
  title: string;
  tags?: string[];
  status?: string;
  extraFrontmatter?: Record<string, unknown>;
  initialBody?: string;
}

function validateScaffold(body: unknown): ScaffoldInput | null {
  if (!body || typeof body !== "object") return null;
  const b = body as Record<string, unknown>;
  if (typeof b.type !== "string" || !VALID_TYPES.has(b.type)) return null;
  if (typeof b.slugSuffix !== "string" || !/^[a-z0-9][a-z0-9-]*$/.test(b.slugSuffix)) return null;
  if (typeof b.title !== "string" || b.title.trim().length === 0) return null;
  return {
    type: b.type,
    slugSuffix: b.slugSuffix,
    title: b.title.trim(),
    tags: Array.isArray(b.tags) ? (b.tags as unknown[]).filter((t): t is string => typeof t === "string") : [],
    status: typeof b.status === "string" ? b.status : undefined,
    extraFrontmatter:
      typeof b.extraFrontmatter === "object" && b.extraFrontmatter !== null
        ? (b.extraFrontmatter as Record<string, unknown>)
        : {},
    initialBody: typeof b.initialBody === "string" ? b.initialBody : undefined,
  };
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

function buildScaffoldFrontmatter(input: ScaffoldInput): string {
  const fm: Record<string, unknown> = {
    type: input.type,
    date: todayIso(),
    tags: input.tags ?? [],
  };
  if (input.status) fm.status = input.status;
  if (input.type === "decision") {
    fm.status = fm.status || "accepted";
    fm["superseded-by"] = null;
  } else if (input.type === "pattern") {
    fm.source = "control-plane-scaffold";
    fm.error_type = null;
    fm.occurrences = 0;
    fm.status = fm.status || "active";
  } else if (input.type === "preference") {
    fm.source = "control-plane-scaffold";
    fm.confidence = "low";
  } else if (input.type === "session") {
    fm.task = null;
    fm.branch = null;
  }
  Object.assign(fm, input.extraFrontmatter ?? {});

  const lines = ["---"];
  for (const [k, v] of Object.entries(fm)) {
    if (Array.isArray(v)) {
      lines.push(`${k}: [${v.map((x) => JSON.stringify(x)).join(", ")}]`);
    } else if (v === null) {
      lines.push(`${k}: null`);
    } else if (typeof v === "string") {
      lines.push(`${k}: ${v}`);
    } else {
      lines.push(`${k}: ${JSON.stringify(v)}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function defaultBody(input: ScaffoldInput): string {
  if (input.type === "decision") {
    return `# ${input.title}

## Context

_Why was this decision needed?_

## Decision

_What was decided?_

## Alternatives Considered

- **Option A** — rejected because…
- **Option B** — rejected because…

## Consequences

- Positive:
- Negative:
- Risks:

## Backlinks

<!-- Auto-generated by scripts/link-index.sh -->
`;
  }
  if (input.type === "pattern") {
    return `# ${input.title}

## Rule

_One-sentence actionable rule._

## Evidence

- [session](../sessions/YYYY-MM-DD-summary.md)

## Applies To

- Languages:
- File types:
- Scenarios:

## Prevention

_How to check if this rule is being followed._

## Backlinks

<!-- Auto-generated by scripts/link-index.sh -->
`;
  }
  if (input.type === "preference") {
    return `# ${input.title}

## What the User Prefers

_Describe the preference concretely._

## How It Was Learned

_What feedback prompted this?_

## When to Apply

- Always / specific languages / specific contexts

## Backlinks

<!-- Auto-generated by scripts/link-index.sh -->
`;
  }
  return `# ${input.title}

## What Was Done

_Brief summary._

## Decisions Made

- [decision](../decisions/YYYY-MM-DD-decision-name.md)

## Patterns Applied

- [pattern](../patterns/pattern-name.md)

## Backlinks

<!-- Auto-generated by scripts/link-index.sh -->
`;
}

async function rescanMemory(db: Db, dojoRoot: string): Promise<number> {
  const scanned = await scanAllMemory(dojoRoot);
  for (const entry of scanned) {
    const existing = await db
      .select()
      .from(memoryEntries)
      .where(eq(memoryEntries.slug, entry.slug))
      .limit(1);
    if (existing.length > 0) {
      await db
        .update(memoryEntries)
        .set({ ...entry, updatedAt: new Date() })
        .where(eq(memoryEntries.slug, entry.slug));
    } else {
      await db.insert(memoryEntries).values(entry);
    }
  }
  return scanned.length;
}

export function memoryRoutes(db: Db, dojoRoot: string) {
  const router = new Hono();

  router.get("/", async (c) => {
    const type = c.req.query("type");
    const search = c.req.query("search");
    const tag = c.req.query("tag");

    const conditions = [];
    if (type) conditions.push(eq(memoryEntries.type, type));
    if (search) conditions.push(ilike(memoryEntries.title, `%${search}%`));

    let query = db.select().from(memoryEntries);
    if (conditions.length > 0) {
      query = query.where(and(...conditions)) as typeof query;
    }
    let results = await query.orderBy(memoryEntries.type, memoryEntries.title);
    if (tag) {
      results = results.filter((r) => r.tags.includes(tag));
    }
    return c.json(results);
  });

  router.get("/graph", async (c) => {
    const all = await db
      .select({
        slug: memoryEntries.slug,
        type: memoryEntries.type,
        title: memoryEntries.title,
      })
      .from(memoryEntries);
    const linkGraph = readLinkGraph(dojoRoot);
    return c.json(buildGraphPayload(all, linkGraph));
  });

  router.get("/tags", async (c) => {
    const all = await db.select({ tags: memoryEntries.tags }).from(memoryEntries);
    const tagSet = new Set<string>();
    for (const row of all) for (const t of row.tags) tagSet.add(t);
    return c.json([...tagSet].sort());
  });

  router.post("/scan", async (c) => {
    const count = await rescanMemory(db, dojoRoot);
    return c.json({ message: "Memory scan complete", count });
  });

  router.post("/scaffold", async (c) => {
    const parsed = validateScaffold(await c.req.json());
    if (!parsed) {
      return c.json(
        {
          error:
            "Invalid scaffold data. Required: type (decision/pattern/preference/session), slugSuffix (lowercase-hyphen), title (non-empty)",
        },
        400
      );
    }

    const folder = VALID_TYPE_FOLDERS[parsed.type];
    const memoryDir = join(dojoRoot, "memory");
    if (!existsSync(memoryDir)) {
      return c.json({ error: "Memory vault not found at " + memoryDir }, 500);
    }

    const filename =
      parsed.type === "decision" || parsed.type === "session"
        ? `${todayIso()}-${parsed.slugSuffix}.md`
        : `${parsed.slugSuffix}.md`;
    const targetDir = join(memoryDir, folder);
    const targetPath = join(targetDir, filename);

    if (existsSync(targetPath)) {
      return c.json({ error: `File already exists: ${folder}/${filename}` }, 409);
    }

    const frontmatter = buildScaffoldFrontmatter(parsed);
    const body = parsed.initialBody?.trim() || defaultBody(parsed);
    const fileContent = `${frontmatter}\n\n${body.trim()}\n`;

    writeFileSync(targetPath, fileContent, "utf-8");

    let linkIndexRan = false;
    const linkScript = join(dojoRoot, "scripts", "link-index.sh");
    if (existsSync(linkScript)) {
      try {
        execSync(`bash ${linkScript}`, { cwd: dojoRoot, stdio: "ignore" });
        linkIndexRan = true;
      } catch {
        // continue — graph just won't have new node until next manual run
      }
    }

    await rescanMemory(db, dojoRoot);

    const slug = `${folder}/${filename.replace(/\.md$/, "")}`;
    return c.json(
      {
        slug,
        path: targetPath,
        linkIndexRan,
      },
      201
    );
  });

  router.get("/:slug{.+}", async (c) => {
    const slug = c.req.param("slug");
    const result = await db
      .select()
      .from(memoryEntries)
      .where(eq(memoryEntries.slug, slug))
      .limit(1);
    if (result.length === 0) return c.json({ error: "Memory entry not found" }, 404);

    const linkGraph = readLinkGraph(dojoRoot);
    const entry = result[0];
    let renderedMarkdown = entry.markdown;
    try {
      renderedMarkdown = readFileSync(entry.filePath, "utf-8").replace(/^---[\s\S]*?---\n?/, "").trim();
    } catch {
      // fall back to DB markdown
    }

    return c.json({
      ...entry,
      markdown: renderedMarkdown,
      backlinks: getBacklinksFor(slug, linkGraph),
      forwardLinks: getForwardLinksFor(slug, linkGraph),
    });
  });

  return router;
}
