"""Generates copilot-instructions.md and copies selected skills/agents to a target project."""

from __future__ import annotations

import shutil
from pathlib import Path

from dojo_cli.scanner import CATEGORIES, INSTRUCTION_SECTIONS, scan_agents, scan_skills


# ── Code standard blocks (embedded so we don't have to parse them out) ─────
_CODE_STANDARDS = {
    "typescript": """\
### TypeScript
- Always use TypeScript with `strict: true`
- Naming: camelCase for variables/functions, PascalCase for components/types
- Styling: Tailwind CSS + shadcn/ui components
- Testing: Write Vitest tests for every new component/logic
- Architecture: Next.js App Router, Server Actions, React Server Components when possible
- Security: Never commit secrets, use environment variables""",
    "python": """\
### Python
- Type hints on all function signatures
- Formatting: Black (line length 88)
- Testing: pytest with fixtures, aim for >80% coverage
- Linting: ruff or flake8
- Architecture: FastAPI or Django conventions as applicable
- Dependency management: pyproject.toml / requirements.txt pinned""",
    "java": """\
### Java
- Follow Google Java Style Guide
- Testing: JUnit 5 + Mockito for unit tests
- Build: Maven or Gradle (match existing project)
- Architecture: Spring Boot patterns, constructor injection
- Security: OWASP dependency check in CI""",
    "go": """\
### Go
- Follow standard library conventions and `go fmt`
- Testing: table-driven tests with `testing` package
- Error handling: explicit, no panic in library code
- Architecture: clean package boundaries, interfaces for testability""",
    "dotnet": """\
### .NET
- Nullable reference types enabled
- Testing: xUnit + FluentAssertions
- Architecture: clean architecture, MediatR for CQRS if applicable
- Security: never log PII, use IOptions pattern for config""",
}


def generate_instructions(
    dojo_root: Path,
    selected_skills: dict[str, list[str]],
    selected_agents: list[str],
    selected_instructions: list[str],
) -> str:
    """Generate copilot-instructions.md content from selections."""
    lines: list[str] = []
    lines.append("# Copilot Instructions")
    lines.append("")
    lines.append("> Generated by `dojo` CLI — Copilot Agents Dojo Skill Marketplace")
    lines.append("")

    # Code standards
    if selected_instructions:
        lines.append("## Code Standards")
        lines.append("")
        for key in selected_instructions:
            if key in _CODE_STANDARDS:
                lines.append(_CODE_STANDARDS[key])
                lines.append("")

    # Skills
    lines.append("## Superpowers Activated")
    lines.append("")
    lines.append("At session start: load selected skills from `skills/`. Follow the mandatory workflow.")
    lines.append("")

    # Mandatory workflow (only if flow-waza skills are selected)
    waza_selected = selected_skills.get("flow-waza", [])
    if waza_selected:
        lines.append("### Mandatory Workflow Pipeline")
        lines.append("")
        lines.append("```")
        lines.append("BRAINSTORM → WORKTREE → PLAN → EXECUTE → TEST → REVIEW → FINISH → LEARN")
        lines.append("```")
        lines.append("")

    # Emit each category
    all_skills = scan_skills(dojo_root)
    for cat_key, cat_info in CATEGORIES.items():
        slugs = selected_skills.get(cat_key, [])
        if not slugs:
            continue

        cat_skills = {s.slug: s for s in all_skills.get(cat_key, [])}
        lines.append(f"### {cat_info['icon']} {cat_info['label']}")
        lines.append("")

        for slug in slugs:
            skill = cat_skills.get(slug)
            if skill:
                lines.append(
                    f"- **[{skill.name}](../skills/{slug}/SKILL.md)**: {skill.description}"
                )
            else:
                lines.append(f"- **{slug}**")
        lines.append("")

    # Agents
    if selected_agents:
        agents = scan_agents(dojo_root)
        agent_map = {a.slug: a for a in agents}
        lines.append("## Active Agents")
        lines.append("")
        for slug in selected_agents:
            agent = agent_map.get(slug)
            if agent:
                lines.append(f"- **[{agent.name}](../agents/{slug}.md)**: {agent.description}")
            else:
                lines.append(f"- **{slug}**")
        lines.append("")

    # Task management
    lines.append("## Task Management")
    lines.append("")
    lines.append("- Use `tasks/todo.md` for the current plan")
    lines.append("- Use `tasks/lessons.md` for the self-improvement log")
    lines.append("- Run `scripts/verify.sh` before marking complete")
    lines.append("")

    return "\n".join(lines)


def apply_to_project(
    dojo_root: Path,
    target_dir: Path,
    selected_skills: dict[str, list[str]],
    selected_agents: list[str],
    selected_instructions: list[str],
) -> list[str]:
    """Copy selected skills/agents to target project and generate instructions."""
    actions: list[str] = []

    # Create target directories
    target_skills = target_dir / "skills"
    target_agents = target_dir / "agents"
    target_github = target_dir / ".github"
    target_tasks = target_dir / "tasks"
    target_scripts = target_dir / "scripts"

    for d in [target_skills, target_agents, target_github, target_tasks, target_scripts]:
        d.mkdir(parents=True, exist_ok=True)

    # Copy selected skills
    for cat_key, slugs in selected_skills.items():
        for slug in slugs:
            src = dojo_root / "skills" / slug
            dst = target_skills / slug
            if src.is_dir():
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)
                actions.append(f"  skills/{slug}/")

    # Copy selected agents
    for slug in selected_agents:
        src = dojo_root / "agents" / f"{slug}.md"
        dst = target_agents / f"{slug}.md"
        if src.exists():
            shutil.copy2(src, dst)
            actions.append(f"  agents/{slug}.md")

    # Copy scaffolding
    for name in ["todo.md", "lessons.md"]:
        src = dojo_root / "tasks" / name
        dst = target_tasks / name
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)
            actions.append(f"  tasks/{name}")

    for name in ["init.sh", "verify.sh", "lesson-updater.sh"]:
        src = dojo_root / "scripts" / name
        dst = target_scripts / name
        if src.exists():
            shutil.copy2(src, dst)
            actions.append(f"  scripts/{name}")

    # Copy skills.md index
    src_index = dojo_root / "skills.md"
    if src_index.exists():
        shutil.copy2(src_index, target_dir / "skills.md")
        actions.append("  skills.md")

    # Generate copilot-instructions.md
    instructions_content = generate_instructions(
        dojo_root, selected_skills, selected_agents, selected_instructions
    )
    instructions_path = target_github / "copilot-instructions.md"
    instructions_path.write_text(instructions_content, encoding="utf-8")
    actions.append("  .github/copilot-instructions.md")

    return actions
