import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { McpServer, ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Store } from "./store.js";

export function registerResources(server: McpServer, store: Store): void {
  server.registerResource(
    "memory-index",
    "memory://INDEX",
    {
      title: "Memory Vault Index",
      description: "Map of Content (auto-generated by scripts/link-index.sh) — read at session start.",
      mimeType: "text/markdown",
    },
    async (uri) => {
      const indexPath = join(store.dojoRoot, "memory", "INDEX.md");
      if (!existsSync(indexPath)) {
        return {
          contents: [
            {
              uri: uri.href,
              mimeType: "text/markdown",
              text: "# Memory Index Missing\n\nRun `bash scripts/link-index.sh` from the dojo root to generate it.",
            },
          ],
        };
      }
      return {
        contents: [
          {
            uri: uri.href,
            mimeType: "text/markdown",
            text: readFileSync(indexPath, "utf-8"),
          },
        ],
      };
    },
  );

  server.registerResource(
    "memory-entry",
    new ResourceTemplate("memory://{type}/{slug}", {
      list: async () => {
        const entries = await store.list();
        return {
          resources: entries.map((e) => ({
            uri: `memory://${e.slug}`,
            name: e.title,
            description: `${e.type} | ${e.tags.join(", ") || "no tags"}`,
            mimeType: "text/markdown",
          })),
        };
      },
    }),
    {
      title: "Memory Entry",
      description: "Individual memory vault entry (decision, pattern, preference, or session).",
      mimeType: "text/markdown",
    },
    async (uri, { type, slug }) => {
      const fullSlug = `${type}/${slug}`;
      const entry = await store.get(fullSlug);
      if (!entry) {
        return {
          contents: [
            {
              uri: uri.href,
              mimeType: "text/markdown",
              text: `# Not Found\n\nNo entry at \`${fullSlug}\`.`,
            },
          ],
        };
      }
      const fm = entry.frontmatter as Record<string, unknown>;
      const fmText = Object.entries(fm)
        .map(([k, v]) => `${k}: ${typeof v === "string" ? v : JSON.stringify(v)}`)
        .join("\n");
      return {
        contents: [
          {
            uri: uri.href,
            mimeType: "text/markdown",
            text: `---\n${fmText}\n---\n\n${entry.markdown}\n`,
          },
        ],
      };
    },
  );
}
