export const CODE_STANDARDS: Record<string, string> = {
  typescript: `## TypeScript Standards
- Use strict mode, no \`any\` types
- Prefer \`const\` over \`let\`, never use \`var\`
- Use async/await over raw Promises
- Export explicit types for all public APIs
- Use template literals over string concatenation`,

  python: `## Python Standards
- Follow PEP 8, use type hints on all functions
- Use pathlib over os.path
- Prefer f-strings over .format()
- Use dataclasses or Pydantic for data structures
- Run black + ruff before committing`,

  java: `## Java Standards
- Follow Google Java Style Guide
- Use records for immutable data
- Prefer Optional over null returns
- Use try-with-resources for AutoCloseable
- Write Javadoc for all public methods`,

  go: `## Go Standards
- Follow Effective Go guidelines
- Use \`errors.Is\`/\`errors.As\` for error checking
- Prefer table-driven tests
- Use context.Context for cancellation
- Run \`go vet\` and \`golangci-lint\` before committing`,

  dotnet: `## .NET Standards
- Follow Microsoft C# coding conventions
- Use nullable reference types
- Prefer pattern matching over type checking
- Use \`IAsyncEnumerable\` for streaming
- Use \`record\` types for DTOs`,
};

export interface SkillInput {
  slug: string;
  name: string;
  markdown: string;
}

export interface AgentInput {
  slug: string;
  name: string;
  markdown: string;
}

export const MEMORY_SESSION_BOOT_BLOCK = `## Memory Vault — Session Boot

This project includes a persistent memory vault at \`memory/\` (decisions, patterns, preferences, sessions).
A Model Context Protocol server (\`dojo-memory\`) is wired up to give you direct, structured access.

**At the start of every session:**
1. Call \`memory_recent_sessions\` (limit 3) to load what the previous agent did.
2. Call \`memory_decisions_active\` to load architectural constraints in force.
3. When you start working in a specific area, call \`memory_patterns_for_context\` with the language and/or file type.

You may also read \`memory://INDEX\` directly for the Map of Content.

**During the session:**
- If you discover a new pattern, decision, or user preference, call \`memory_create\` to persist it.
- If a new decision overrides an old one, call \`memory_supersede\`.
- Use \`memory_link\` to connect related entries.

**At the end of meaningful work — Session Checkpoint:**
Call \`memory_create({ type: "session", slugSuffix: "<short-kebab>", title: "...", tags: [...], initialBody: "..." })\`
with a concise summary covering: what was done, decisions made, patterns applied/discovered, links to entries you read or created.
This is the time-machine entry the next agent will load.
`;

export function generateInstructions(
  skills: SkillInput[],
  agents: AgentInput[],
  codeStandards: Record<string, boolean>,
  options?: { memoryEnabled?: boolean }
): string {
  const sections: string[] = [];

  sections.push("# Copilot Instructions\n");
  sections.push("> Generated by Dojo Control Plane\n");

  // Code standards
  const activeStandards = Object.entries(codeStandards)
    .filter(([, enabled]) => enabled)
    .map(([lang]) => CODE_STANDARDS[lang])
    .filter(Boolean);

  if (activeStandards.length > 0) {
    sections.push("---\n");
    sections.push("# Code Standards\n");
    sections.push(activeStandards.join("\n\n"));
    sections.push("");
  }

  // Memory boot block
  if (options?.memoryEnabled) {
    sections.push("---\n");
    sections.push("# Memory\n");
    sections.push(MEMORY_SESSION_BOOT_BLOCK);
    sections.push("");
  }

  // Skills
  if (skills.length > 0) {
    sections.push("---\n");
    sections.push("# Skills\n");
    for (const skill of skills) {
      sections.push(skill.markdown);
      sections.push("");
    }
  }

  // Agents
  if (agents.length > 0) {
    sections.push("---\n");
    sections.push("# Agents\n");
    for (const agent of agents) {
      sections.push(agent.markdown);
      sections.push("");
    }
  }

  return sections.join("\n");
}
