#!/usr/bin/env bash
# Copilot Agents Dojo — RTM Generator (v1)
#
# Emits the Requirements Traceability Matrix as docs/rtm-<engagement>.md
# directly from the artifact graph. The RTM is a byproduct of the gate,
# never a hand-written document.
#
# Usage:
#   bash scripts/gen-rtm.sh                             # all engagements
#   bash scripts/gen-rtm.sh requirements/<engagement>   # one engagement
#
# Output: docs/rtm-<engagement>.md (one file per engagement)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOJO_ROOT="${DOJO_ROOT:-$(dirname "$SCRIPT_DIR")}"
cd "$DOJO_ROOT"

TARGETS=("$@")
if [ "${#TARGETS[@]}" -eq 0 ]; then
  if [ -d requirements ]; then
    while IFS= read -r d; do TARGETS+=("$d"); done < <(find requirements -mindepth 1 -maxdepth 1 -type d)
  fi
fi

[ "${#TARGETS[@]}" -eq 0 ] && { echo "no engagements"; exit 0; }

mkdir -p docs

yaml_value() {
  awk -v k="$2" '
    BEGIN { in_fm=0 }
    /^---[[:space:]]*$/ { in_fm++; next }
    in_fm == 1 && $0 ~ "^"k":" {
      sub("^"k":[[:space:]]*", "")
      gsub(/^["'\'']|["'\'']$/, "")
      print; exit
    }
  ' "$1"
}

yaml_array() {
  awk -v k="$2" '
    BEGIN { in_fm=0 }
    /^---[[:space:]]*$/ { in_fm++; next }
    in_fm == 1 && $0 ~ "^"k":" {
      sub("^"k":[[:space:]]*", "")
      gsub(/^\[|\]$/, "")
      gsub(/,/, " ")
      gsub(/["'\'']/, "")
      print; exit
    }
  ' "$1"
}

emit_rtm() {
  local eng="$1"
  local name; name=$(basename "$eng")
  local out="docs/rtm-${name}.md"

  {
    echo "# Requirements Traceability Matrix — $name"
    echo ""
    echo "> Auto-generated by \`scripts/gen-rtm.sh\` from"
    echo "> \`$eng/\`. Do not edit by hand. Regenerate after every"
    echo "> change to a requirement artifact."
    echo ""
    echo "| ID | Layer | Title | Parents | Owner | Ratified | Target |"
    echo "|---|---|---|---|---|---|---|"
  } > "$out"

  for layer in BR FR NFR SR IR TR; do
    local files
    files=$(find "$eng/$layer" -maxdepth 1 -type f -name '*.md' 2>/dev/null | sort || true)
    [ -z "$files" ] && continue
    while IFS= read -r f; do
      [ -z "$f" ] && continue
      local id title parents owner ratified target
      id=$(yaml_value "$f" id)
      title=$(yaml_value "$f" title)
      parents=$(yaml_array "$f" parent_ids)
      owner=$(yaml_value "$f" owner)
      ratified=$(yaml_value "$f" ratified_by)
      target=$(yaml_value "$f" target)
      [ -z "$parents" ] && parents="—" || parents=$(echo "$parents" | sed -E 's/[[:space:]]+/, /g')
      [ -z "$ratified" ] && ratified="*unratified*"
      [ -z "$target" ] && target="—"
      echo "| \`$id\` | $layer | $title | $parents | $owner | $ratified | $target |" >> "$out"
    done <<< "$files"
  done

  echo "wrote $out"
}

for t in "${TARGETS[@]}"; do
  emit_rtm "$t"
done
