#!/usr/bin/env bash
# Copilot Agents Dojo — Lesson Updater (cache-aware skill amendments)
#
# Scans tasks/lessons.md for entries where occurrences >= 3 and status is
# active, groups by related_skill, and emits an amendment proposal.
#
# Default mode: DEFERRED — proposals are written to .dojo/pending-amendments.md
# and applied on next session start. This preserves Copilot's prompt cache.
#
# --now mode: applies amendments immediately by appending a "Lessons Absorbed"
# block to the relevant SKILL.md. Prints a loud cache-invalidation warning.
#
# Usage:
#   bash scripts/lesson-updater.sh               # deferred (default)
#   bash scripts/lesson-updater.sh --now         # apply immediately (cache-busting)
#   bash scripts/lesson-updater.sh --threshold 5 # require 5+ occurrences

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOJO_ROOT="${DOJO_ROOT:-$(dirname "$SCRIPT_DIR")}"
cd "$DOJO_ROOT"

LESSONS="tasks/lessons.md"
PENDING=".dojo/pending-amendments.md"
USAGE=".dojo/skill-usage.json"
THRESHOLD=3
NOW=false

while [ $# -gt 0 ]; do
  case "$1" in
    --now)        NOW=true; shift ;;
    --threshold)  THRESHOLD="$2"; shift 2 ;;
    -h|--help)    sed -n '1,20p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

mkdir -p .dojo
[ -f "$LESSONS" ] || { echo "❌ $LESSONS not found — run scripts/init.sh" >&2; exit 1; }

# Parse lessons.md YAML blocks (ignore commented-out template entries).
# Emit one line per qualifying lesson: related_skill|occurrences|rule
parse_lessons() {
  awk -v thresh="$THRESHOLD" '
    BEGIN { in_block = 0; in_comment = 0 }
    /^<!--/ { in_comment = 1 }
    /-->$/  { in_comment = 0; next }
    in_comment { next }

    /^- date:/ {
      if (in_block && occ + 0 >= thresh && status == "active" && skill != "") {
        gsub(/\|/, "/", rule)
        print skill "|" occ "|" rule
      }
      in_block = 1; occ = 0; status = ""; skill = ""; rule = ""
      next
    }
    in_block && /^[[:space:]]+occurrences:/      { occ    = $2 + 0 }
    in_block && /^[[:space:]]+status:/           { status = $2 }
    in_block && /^[[:space:]]+related_skill:/    { skill  = $2 }
    in_block && /^[[:space:]]+rule:/ {
      sub(/^[[:space:]]+rule:[[:space:]]*/, "")
      gsub(/^"/, ""); gsub(/"$/, "")
      rule = $0
    }
    END {
      if (in_block && occ + 0 >= thresh && status == "active" && skill != "") {
        gsub(/\|/, "/", rule)
        print skill "|" occ "|" rule
      }
    }
  ' "$LESSONS"
}

PROPOSALS=$(parse_lessons || true)

if [ -z "$PROPOSALS" ]; then
  echo "✅ no patterns at occurrences >= $THRESHOLD with related_skill set."
  exit 0
fi

# Bump telemetry: lessons_logged + last_lesson_at per skill.
if command -v jq >/dev/null 2>&1 && [ -f "$USAGE" ]; then
  tmp=$(mktemp)
  ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "$PROPOSALS" | awk -F'|' '{print $1}' | sort -u | while IFS= read -r skill; do
    [ -z "$skill" ] && continue
    jq --arg n "$skill" --arg t "$ts" '
      .skills[$n] = (.skills[$n] // {uses:0,last_used:null,lessons_logged:0,last_lesson_at:null,pinned:false})
      | .skills[$n].lessons_logged += 1
      | .skills[$n].last_lesson_at = $t
    ' "$USAGE" > "$tmp" && mv "$tmp" "$USAGE"
  done
fi

emit_proposal_block() {
  echo "## Amendment proposal — $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  echo "Generated by \`scripts/lesson-updater.sh\` (threshold=$THRESHOLD)."
  echo ""
  echo "| Skill | Occurrences | Rule to absorb |"
  echo "|---|---:|---|"
  echo "$PROPOSALS" | sort -t'|' -k1,1 -k2,2nr | while IFS='|' read -r skill occ rule; do
    echo "| \`$skill\` | $occ | $rule |"
  done
  echo ""
  echo "Apply by editing each \`SKILL.md\` to absorb the rule. After landing the amendment, set the source lesson's \`status: amended-to-skill\` in \`tasks/lessons.md\`."
  echo ""
}

if $NOW; then
  cat <<'WARN' >&2
⚠️  --now: applying amendments immediately. This INVALIDATES Copilot's prompt
   cache for every session that has these skills loaded. Cost will rise on the
   next turn. Default (deferred) is safer — re-run without --now if unsure.
WARN
  echo "$PROPOSALS" | sort -t'|' -k1,1 -k2,2nr | while IFS='|' read -r skill occ rule; do
    path=""
    for parent in skills optional-skills; do
      [ -f "$parent/$skill/SKILL.md" ] && path="$parent/$skill/SKILL.md"
    done
    [ -z "$path" ] && { echo "  ⚠️  skill not found on disk: $skill — skipping" >&2; continue; }
    if ! grep -q "^## Lessons Absorbed" "$path"; then
      printf "\n## Lessons Absorbed\n\n" >> "$path"
    fi
    printf -- "- (%s, occurrences=%s) %s\n" "$(date -u +%Y-%m-%d)" "$occ" "$rule" >> "$path"
    echo "  ✏️  absorbed into $path"
  done
  echo "↻  Run: bash scripts/regen-skills-index.sh && bash scripts/verify.sh spec"
else
  [ -f "$PENDING" ] || printf "# Pending Skill Amendments\n\nGenerated by \`scripts/lesson-updater.sh\`. Apply via \`--now\` on the next session start (not mid-session).\n\n" > "$PENDING"
  emit_proposal_block >> "$PENDING"
  count=$(echo "$PROPOSALS" | wc -l | tr -d ' ')
  echo "📥 wrote $count amendment proposal(s) to $PENDING (deferred — safe for current session)"
  echo "ℹ️  Apply on next session start: bash scripts/lesson-updater.sh --now"
fi
