#!/usr/bin/env bash
# Copilot Agents Dojo — Link Index Builder
# Scans memory/ vault for markdown links, builds a link graph,
# appends backlink sections, and updates INDEX.md stats.
#
# Usage: bash scripts/link-index.sh
#
# This script replaces Obsidian's graph engine with a plain-text
# equivalent that any agent can query.
# Compatible with macOS (bash 3.x) and Linux.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
MEMORY_DIR="$REPO_ROOT/memory"
INDEX_FILE="$MEMORY_DIR/INDEX.md"
GRAPH_FILE="$MEMORY_DIR/.link-graph.json"

if [ ! -d "$MEMORY_DIR" ]; then
  echo "❌ No memory/ directory found at $MEMORY_DIR"
  exit 1
fi

echo "🔗 Copilot Agents Dojo — Link Index Builder"
echo "   Scanning $MEMORY_DIR for links..."

# ─── Use python3 for reliable cross-platform link extraction ───
export MEMORY_DIR INDEX_FILE GRAPH_FILE
python3 << 'PYEOF'
import os, re, json
from datetime import datetime, timezone

memory_dir = os.environ["MEMORY_DIR"]
index_file = os.environ["INDEX_FILE"]
graph_file = os.environ["GRAPH_FILE"]

# Collect all markdown files (exclude templates)
md_files = []
for root, dirs, files in os.walk(memory_dir):
    for f in files:
        if f.endswith('.md') and f != '_template.md':
            md_files.append(os.path.join(root, f))
md_files.sort()

total_files = len(md_files)
total_links = 0
forward_links = {}  # rel_path -> [targets]
back_links = {}     # rel_path -> set(sources)

# Extract [text](target.md) links, skipping those inside backticks or code blocks
link_re = re.compile(r'\[([^\]]*)\]\(([^)]*\.md)\)')
code_block_re = re.compile(r'```.*?```', re.DOTALL)
inline_code_re = re.compile(r'`[^`]+`')

for filepath in md_files:
    rel_path = os.path.relpath(filepath, memory_dir)
    file_dir = os.path.dirname(rel_path)

    with open(filepath, 'r', errors='replace') as fh:
        content = fh.read()

    # Strip code blocks and inline code before extracting links
    clean_content = code_block_re.sub('', content)
    clean_content = inline_code_re.sub('', clean_content)

    targets = []
    for match in link_re.finditer(clean_content):
        target = match.group(2)
        # Resolve relative path
        if file_dir and file_dir != '.':
            resolved = os.path.normpath(os.path.join(file_dir, target))
        else:
            resolved = os.path.normpath(target)
        targets.append(resolved)
        total_links += 1

        if resolved not in back_links:
            back_links[resolved] = set()
        back_links[resolved].add(rel_path)

    if targets:
        forward_links[rel_path] = targets

# Write .link-graph.json
graph = {
    "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "total_files": total_files,
    "total_links": total_links,
    "forward_links": forward_links,
    "back_links": {k: sorted(v) for k, v in back_links.items()},
}
with open(graph_file, 'w') as f:
    json.dump(graph, f, indent=2)

print(f"   ✅ Link graph written to memory/.link-graph.json")

# Update backlink sections in each file
MARKER = "<!-- Auto-generated by scripts/link-index.sh -->"

for filepath in md_files:
    rel_path = os.path.relpath(filepath, memory_dir)
    sources = sorted(back_links.get(rel_path, set()))
    file_dir = os.path.dirname(rel_path)

    if not sources:
        backlink_content = f"{MARKER}\n_No backlinks yet._\n"
    else:
        lines = [MARKER]
        for src in sources:
            if file_dir and file_dir != '.':
                link_path = os.path.relpath(src, file_dir)
            else:
                link_path = src
            src_name = os.path.splitext(os.path.basename(src))[0]
            lines.append(f"- [{src_name}]({link_path})")
        backlink_content = "\n".join(lines) + "\n"

    with open(filepath, 'r', errors='replace') as fh:
        content = fh.read()

    if MARKER in content:
        # Remove everything from marker to EOF and replace
        idx = content.index(MARKER)
        content = content[:idx] + backlink_content
        with open(filepath, 'w') as fh:
            fh.write(content)

print(f"   ✅ Backlink sections updated")

# Count by category
def count_in(subdir):
    d = os.path.join(memory_dir, subdir)
    if not os.path.isdir(d):
        return 0
    return len([f for f in os.listdir(d) if f.endswith('.md') and f != '_template.md'])

counts = {
    "decisions": count_in("decisions"),
    "patterns": count_in("patterns"),
    "preferences": count_in("preferences"),
    "sessions": count_in("sessions"),
}

# Update INDEX.md stats
if os.path.exists(index_file):
    with open(index_file, 'r') as fh:
        idx_content = fh.read()

    replacements = {
        "Total files": str(total_files),
        "Decisions": str(counts["decisions"]),
        "Patterns": str(counts["patterns"]),
        "Preferences": str(counts["preferences"]),
        "Sessions": str(counts["sessions"]),
        "Total links": str(total_links),
    }
    for label, value in replacements.items():
        idx_content = re.sub(
            rf'\| {label} \| \d+ \|',
            f'| {label} | {value} |',
            idx_content
        )

    # Update last-updated
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    idx_content = re.sub(r'^last-updated:.*$', f'last-updated: {now}', idx_content, flags=re.MULTILINE)

    with open(index_file, 'w') as fh:
        fh.write(idx_content)

print(f"   ✅ INDEX.md stats updated")
print()
print(f"📊 Memory vault: {total_files} files, {total_links} links")
print(f"   Decisions: {counts['decisions']} | Patterns: {counts['patterns']} | Preferences: {counts['preferences']} | Sessions: {counts['sessions']}")
PYEOF
