#!/usr/bin/env bash
# Copilot Agents Dojo — Obsidian Sync
# Bridges tasks/lessons.md into the memory vault by scanning for
# patterns ready for promotion (3+ occurrences) and syncing them
# as candidate pattern files.
#
# Usage: bash scripts/obsidian-sync.sh
#
# This script:
#   1. Reads tasks/lessons.md for entries with occurrences >= 3
#   2. Creates candidate pattern files in memory/patterns/ (if not already promoted)
#   3. Runs link-index.sh to rebuild the graph
#
# Safe to run repeatedly — it won't overwrite existing pattern files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
LESSONS_FILE="$REPO_ROOT/tasks/lessons.md"
PATTERNS_DIR="$REPO_ROOT/memory/patterns"
TODAY=$(date -u +%Y-%m-%d)

if [ ! -f "$LESSONS_FILE" ]; then
  echo "❌ No lessons.md found at $LESSONS_FILE"
  echo "   Run scripts/init.sh first."
  exit 1
fi

echo "🔄 Copilot Agents Dojo — Obsidian Sync"
echo "   Scanning lessons for promotion candidates..."

# Parse lessons.md for YAML entries with occurrences >= 3
# Extract blocks: date, error_type, trigger, root_cause, fix, rule, occurrences, status
PROMOTED=0
SKIPPED=0

# Use awk to extract lesson blocks with occurrences >= 3 and status != amended-to-skill
awk '
/^- date:/ { block=""; in_block=1 }
in_block {
  block = block $0 "\n"
  if (/occurrences:/) {
    split($0, a, ":")
    gsub(/[^0-9]/, "", a[2])
    occ = a[2] + 0
  }
  if (/status:/) {
    split($0, a, ":")
    gsub(/^[ \t]+|[ \t]+$/, "", a[2])
    status = a[2]
  }
  if (/rule:/) {
    split($0, a, "\"")
    rule = a[2]
  }
  if (/error_type:/) {
    split($0, a, ":")
    gsub(/^[ \t]+|[ \t]+$/, "", a[2])
    error_type = a[2]
  }
  if (/trigger:/) {
    split($0, a, "\"")
    trigger = a[2]
  }
  # End of block detection: next entry or end of file
  if (/^$/ || /^- date:/ && NR > 1) {
    if (occ >= 3 && status != "amended-to-skill") {
      print error_type "|" rule "|" trigger "|" occ
    }
    if (/^- date:/) {
      block = $0 "\n"
      occ = 0; status = ""; rule = ""; error_type = ""; trigger = ""
    } else {
      in_block = 0
    }
  }
}
END {
  if (in_block && occ >= 3 && status != "amended-to-skill") {
    print error_type "|" rule "|" trigger "|" occ
  }
}
' "$LESSONS_FILE" | while IFS='|' read -r error_type rule trigger occ; do
  # Skip empty
  [ -z "$rule" ] && continue

  # Generate filename from error_type
  slug=$(echo "$error_type" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')
  [ -z "$slug" ] && slug="unnamed-pattern"
  filename="$PATTERNS_DIR/${slug}.md"

  # Don't overwrite existing promoted patterns
  if [ -f "$filename" ]; then
    SKIPPED=$((SKIPPED + 1))
    echo "   ⏭️  Already promoted: $slug"
    continue
  fi

  # Create pattern file from template
  cat > "$filename" << EOF
---
type: pattern
date: $TODAY
source: tasks/lessons.md
error_type: $error_type
occurrences: $occ
status: active
tags: [$error_type]
---

# Pattern: ${error_type}

## Rule

${rule:-No rule captured — review tasks/lessons.md and add one.}

## Evidence

Trigger: ${trigger:-See tasks/lessons.md}
Occurrences: ${occ}

## Applies To

- Review and fill in applicable languages, file types, scenarios

## Prevention

How to check if this rule is being followed — fill in after review.

## Backlinks

<!-- Auto-generated by scripts/link-index.sh -->
EOF

  PROMOTED=$((PROMOTED + 1))
  echo "   ✅ Promoted: $slug ($occ occurrences)"
done

echo ""
echo "📊 Sync complete. Promoted: $PROMOTED | Already existed: $SKIPPED"

# Rebuild link index
if [ -f "$SCRIPT_DIR/link-index.sh" ]; then
  echo ""
  bash "$SCRIPT_DIR/link-index.sh"
fi
