#!/usr/bin/env bash
# Copilot Agents Dojo — Regenerate slash-command prompt shims.
#
# Scans skills/*/SKILL.md and agents/*.md, reads their YAML frontmatter, and
# emits one GitHub Copilot prompt file per skill and per persona under
# .github/prompts/. Each file becomes a discoverable slash command — e.g.
# /dojo-debugging or /dojo-agent-architect — that tells Copilot to load and
# apply the underlying SKILL.md or agent persona.
#
# Output is deterministic (sorted, no timestamps) so it diffs cleanly and a
# --check run can gate drift in CI.
#
# Usage:
#   bash scripts/regen-prompts.sh            # write .github/prompts/*.prompt.md
#   bash scripts/regen-prompts.sh --check    # exit 1 if the tree is out of date
#   bash scripts/regen-prompts.sh --stdout   # list the shims that would exist
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOJO_ROOT="${DOJO_ROOT:-$(dirname "$SCRIPT_DIR")}"
cd "$DOJO_ROOT"

PROMPTS_DIR=".github/prompts"

MODE="write"
for arg in "$@"; do
  case "$arg" in
    --check)  MODE="check" ;;
    --stdout) MODE="stdout" ;;
    -h|--help) sed -n '1,18p' "$0"; exit 0 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# --- helpers --------------------------------------------------------------

# Pull a single key from the YAML frontmatter of a markdown file.
fm_get() {
  local file="$1" key="$2"
  awk -v key="$key" '
    /^---$/ { c++; next }
    c == 1 && $0 ~ "^"key":" {
      sub("^"key":[[:space:]]*", "")
      sub(/^"/, ""); sub(/"$/, "")
      sub(/^>-[[:space:]]*/, "")
      print
      exit
    }
  ' "$file"
}

# Escape a value for use inside a single-quoted YAML scalar.
yq() { printf "%s" "$1" | sed "s/'/''/g"; }

# Keep only the first sentence of a (possibly long) description.
first_sentence() { printf "%s" "$1" | sed -E 's/\. .*/./'; }

emit_skill() {
  local id="$1" name="$2" desc="$3"
  cat <<EOF
---
mode: agent
description: '$(yq "$desc")'
---
<!-- Auto-generated by scripts/regen-prompts.sh from skills/$id/SKILL.md. Do not edit by hand. -->

Activate the **$name** dojo skill.

Read [\`skills/$id/SKILL.md\`](../../skills/$id/SKILL.md) in full, then apply its procedure to the current request. Honour its When to Use, Procedure, Pitfalls, and Verification sections — do not skip the verification step.
EOF
}

emit_agent() {
  local slug="$1" name="$2" desc="$3"
  cat <<EOF
---
mode: agent
description: '$(yq "$desc")'
---
<!-- Auto-generated by scripts/regen-prompts.sh from agents/$slug.md. Do not edit by hand. -->

Adopt the **$name** agent persona.

Read [\`agents/$slug.md\`](../../agents/$slug.md) and operate as that persona — its responsibilities, activation criteria, and standards — for the current request.
EOF
}

# Generate the full set of shims into a destination directory.
write_all() {
  local dest="$1"
  mkdir -p "$dest"
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    local id name desc
    id=$(basename "$(dirname "$f")")
    name=$(fm_get "$f" name)
    desc=$(fm_get "$f" description)
    emit_skill "$id" "$name" "$desc" > "$dest/dojo-$id.prompt.md"
  done < <(find skills -mindepth 2 -maxdepth 2 -name SKILL.md 2>/dev/null | sort)

  while IFS= read -r f; do
    [ -z "$f" ] && continue
    local slug name desc
    slug=$(basename "$f" .md)
    name=$(fm_get "$f" name)
    desc=$(first_sentence "$(fm_get "$f" description)")
    emit_agent "$slug" "$name" "$desc" > "$dest/dojo-agent-$slug.prompt.md"
  done < <(find agents -maxdepth 1 -name '*.md' 2>/dev/null | sort)
}

# --- modes ----------------------------------------------------------------

case "$MODE" in
  write)
    mkdir -p "$PROMPTS_DIR"
    find "$PROMPTS_DIR" -maxdepth 1 -name 'dojo-*.prompt.md' -delete 2>/dev/null || true
    write_all "$PROMPTS_DIR"
    count=$(find "$PROMPTS_DIR" -maxdepth 1 -name 'dojo-*.prompt.md' | wc -l | tr -d ' ')
    echo "✅ .github/prompts regenerated ($count slash-command shims)"
    ;;
  stdout)
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    write_all "$tmp"
    (cd "$tmp" && find . -name 'dojo-*.prompt.md' | sed 's|^\./|.github/prompts/|' | sort)
    ;;
  check)
    if [ ! -d "$PROMPTS_DIR" ]; then
      echo "❌ .github/prompts missing — run scripts/regen-prompts.sh" >&2
      exit 1
    fi
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    write_all "$tmp"
    if diff -r "$tmp" "$PROMPTS_DIR" >/dev/null 2>&1; then
      echo "✅ .github/prompts matches skills/ and agents/"
    else
      echo "❌ .github/prompts drift — run scripts/regen-prompts.sh" >&2
      diff -r "$tmp" "$PROMPTS_DIR" >&2 || true
      exit 1
    fi
    ;;
esac
